version: "1"
services:
  frontend:
    build: .
  apache:
    image: bitnami/apache:latest
    ports:
      - "80:8080"
    volumes:
      - ./myapp.conf:/vhosts/myapp.conf:ro
      - .:/app
    depends_on:
      - frontend
