version: "1"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GCLOUD_PROJECT_ID=
      - GCLOUD_STORAGE_BUCKET=
      - DB_HOST=
      - DB_NAME=
      - DB_PASSWORD=
