version: "1"
services:
  backend:
    build: .
    ports:
      - "80:80"
    environment:
      - PORT=80
      - GCLOUD_PROJECT_ID=
      - GCLOUD_STORAGE_BUCKET=
      - DB_HOST=
      - DB_USER=
      - DB_NAME=
      - DB_PASSWORD=
